import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import { Assistant } from "next/font/google";
import "./globals.css";
import FloatingWhatsapp from "@/features/footer/components/floating-whatsapp";
import { QueryProvider } from "@/providers/query-provider";
import { Toaster } from "sonner";
import CartInitializer from "@/features/carts/components/cart-initializer";
import SessionSync from "@/features/auth/components/session-sync";

const assistant = Assistant({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const l = await getLocale();
  return (
    <html
      lang={l}
      dir={l === "ar" ? "rtl" : "ltr"}
      className="overflow-x-hidden"
    >
      <body className={`${assistant.className} antialiased overflow-x-hidden`}>
        <QueryProvider>
          <SessionSync />
          <CartInitializer />
          <NextIntlClientProvider>
            {children}
            <FloatingWhatsapp />
          </NextIntlClientProvider>
          <Toaster position="top-center" richColors />
        </QueryProvider>
      </body>
    </html>
  );
}
